title: Mathias Marty
email: mathiasmarty99@gmail.com
description: Recent EPFL Graduate in Cybersecurity
author: Mathias Marty
skin: Daylight

plainwhite:
  name: Mathias Marty
  tagline: TODO
  date_format: "%b %-d, %Y"
  navigation:
    - title: Resume
      url: "/resume"
   portfolio_image:  "assets/portfolio.png"


plugins:
  - jekyll-remote-theme
  
remote_theme: samarsault/plainwhite-jekyll
