title: Mathias Marty
email: mathiasmarty99@gmail.com
description: Recent EPFL/ETHZ Graduate in Cybersecurity
author: Mathias Marty
skin: Daylight

plainwhite:
  name: Mathias Marty
  tagline: |
    First Line. 
  
    Second Line. 
  
    Third Line.
  date_format: "%b %-d, %Y"
  navigation:
    - title: Resume
      url: "/assets/CV.pdf"
  portfolio_image:  "assets/portfolio.png"


plugins:
  - jekyll-remote-theme
  
remote_theme: samarsault/plainwhite-jekyll
